name: StillUp Site Monitor

on:
  schedule:
    - cron: '*/30 * * * *' # This runs every 30 minutes
  workflow_dispatch:      # This adds a "Run Now" button in GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install supabase requests

      - name: Run Pinger
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python pinger.py